version: '3.8'

services:
    app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        volumes:
            - ./:/app
        links:
            - server

    server:
        build:
            context: ./tests/Server
            dockerfile: ./Dockerfile
        volumes:
            - ./tests/Server:/app
        expose:
            - 8888
        ports:
            - "8888:8888"
        command: php -S 0.0.0.0:8888 -t /app index.php
