version: '3.8'

services:
    app:
        build:
            context: ./
            dockerfile: ./runtimes/php7/Dockerfile
        environment:
            - TESTING_SERVER_URL=http://server:8888
        volumes:
            - ./:/app
        links:
            - server

    php8:
        build:
            context: ./
            dockerfile: ./runtimes/php8/Dockerfile
        environment:
            - TESTING_SERVER_URL=http://server:8888
        volumes:
            - ./:/app
        links:
            - server

    server:
        image: node:16-alpine
        volumes:
            - ./:/app
        expose:
            - 8888
        ports:
            - "8888:8888"
        command: node /app/tests/server/index.js
