version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: .docker/${PHP_VERSION:-php7.1}/Dockerfile
    environment:
      - TESTING_SERVER_URL=http://server:8000
    volumes:
      - ./:/app
    links:
      - server

  server:
    image: node:16-alpine
    volumes:
      - ./:/app
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: node /app/tests/server.js
