name: PHP CS Fixer

on: [ push, pull_request ]

jobs:
  php-cs-fixer:
    name: Run PHP CS Fixer

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress

      - name: Run PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff-format udiff
