name: PHPUnit

on: [ push, pull_request ]

jobs:
  tests:
    name: OS ${{ matrix.os }}, PHP ${{ matrix.php }}, ${{ matrix.dependencies }} dependencies

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php: [ '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2' ]
        dependencies: [ lowest, highest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Start testing server on Ubuntu OS
        if: matrix.os == 'ubuntu-latest'
        run: node tests/server.js &

      - name: Start testing server on Windows OS
        if: matrix.os == 'windows-latest'
        run: Start-Process -NoNewWindow node tests/server.js

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo
          coverage: none

      - name: Install Composer dependencies with the highest versions
        if: matrix.dependencies == 'highest'
        run: composer update --no-interaction --no-progress

      - name: Install Composer dependencies with the lowest stable versions
        if: matrix.dependencies == 'lowest'
        run: composer update --no-interaction --no-progress --prefer-lowest --prefer-stable

      - name: Run PHPUnit
        run: vendor/bin/phpunit

  coverage:
    name: Analyze code coverage

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Start testing server
        run: node tests/server.js &

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer update --no-interaction --no-progress

      - name: Run PHPUnit with a coverage analysis
        run: vendor/bin/phpunit --coverage-clover coverage.xml

      - name: Upload the coverage report
        uses: codecov/codecov-action@v3
