name: PHPUnit

on: [ push, pull_request ]

jobs:
  tests:
    name: OS ${{ matrix.os }}, PHP ${{ matrix.php }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php: [ '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2' ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo
          coverage: none

      - name: Install Composer dependencies
        run: composer update --no-interaction --no-progress

      - name: Set up Node.JS
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Start testing server
        run: node tests/server.js &

      - name: Run PHPUnit
        run: vendor/bin/phpunit

  coverage:
    name: Analyze code coverage

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer update --no-interaction --no-progress

      - name: Set up Node.JS
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Start testing server
        run: node tests/server.js &

      - name: Run PHPUnit with a coverage analysis
        run: vendor/bin/phpunit --coverage-clover coverage.xml

      - name: Upload the coverage report
        uses: codecov/codecov-action@v3
