name: Tests

on: [ push, pull_request ]

jobs:
  tests:
    name: OS ${{ matrix.os }}, PHP ${{ matrix.php }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php: [ '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1' ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo
          coverage: pcov

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Start testing server
        run: node tests/server/index.js &

      - name: Execute tests
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Code coverage
        run: "bash <(curl -s https://codecov.io/bash)"
