name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php: [ '7.0', '7.1' ]
        prefer: [ prefer-lowest, prefer-stable ]

    name: OS ${{ matrix.os }}, PHP ${{ matrix.php }}, ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo
          coverage: pcov

      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --no-progress --prefer-source

      - name: Execute tests
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Code coverage
        run: "bash <(curl -s https://codecov.io/bash)"
